--------------------------------------------------------
--  Constraints for Table AIRLINES
--------------------------------------------------------

  ALTER TABLE "C##FLIGHT"."AIRLINES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##FLIGHT"."AIRLINES" ADD CHECK (ActivationStatus IN ('Pending', 'Approved', 'Denied')) ENABLE;
  ALTER TABLE "C##FLIGHT"."AIRLINES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
