--------------------------------------------------------
--  Ref Constraints for Table FLIGHT
--------------------------------------------------------

  ALTER TABLE "C##FLIGHT"."FLIGHT" ADD FOREIGN KEY ("AIRLINEID")
	  REFERENCES "C##FLIGHT"."AIRLINES" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##FLIGHT"."FLIGHT" ADD FOREIGN KEY ("DEPARTUREAIRPORTID")
	  REFERENCES "C##FLIGHT"."AIRPORT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##FLIGHT"."FLIGHT" ADD FOREIGN KEY ("DESTINATIONAIRPORTID")
	  REFERENCES "C##FLIGHT"."AIRPORT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##FLIGHT"."FLIGHT" ADD FOREIGN KEY ("DEGREEID")
	  REFERENCES "C##FLIGHT"."DEGREE" ("ID") ON DELETE SET NULL ENABLE;
