--------------------------------------------------------
--  File created - Thursday-November-14-2024   
--------------------------------------------------------
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DROP.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ABOUTUS.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRLINES.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRPORT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\BANK.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CITY.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CONTACTUS.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\COUNTRY.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_FACILITIES.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FACILITY.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FLIGHT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\HOME.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\LOGIN.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\PARTNER.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\RESERVATION.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ROLE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\TESTIMONIAL.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\USERS.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CITY_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\COUNTRY_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FACILITY_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRLINES_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRPORT_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ROLE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\USERS_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FLIGHT_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ABOUTUS_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\BANK_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CONTACTUS_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_FACILITIES_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\HOME_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\LOGIN_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\PARTNER_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\RESERVATION_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\TESTIMONIAL_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008704.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008706.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008709.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008712.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008714.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008716.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008721.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008723.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008725.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008728.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008731.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008734.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008736.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008738.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008740.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008742.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008747.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008753.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008736_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008721_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008709_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008740_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008706_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008738_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008704_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008723_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008742_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008725_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008747_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008734_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008716_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008731_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008753_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008712_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008728_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\SYS_C008714_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\UPDATEFLIGHTSTATUS.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ABOUT_PKG.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRLINE_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRPORT_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\BANK_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CITY_PKG.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CONTACT_PKG.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\COUNTRY_PKG.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_FACILITY_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FACILITY_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FLIGHT_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\HOME_PAGE_PKG.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\LOGIN_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\PARTENER_PKG.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\RESERVATION_PACKAGE.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\TESTIMONIALS_PKG.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\USER_PKG.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ABOUT_PKG_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRLINE_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRPORT_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\BANK_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CITY_PKG_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CONTACT_PKG_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\COUNTRY_PKG_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_FACILITY_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FACILITY_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FLIGHT_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\HOME_PAGE_PKG_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\LOGIN_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\PARTENER_PKG_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\RESERVATION_PACKAGE_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\TESTIMONIALS_PKG_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\USER_PKG_1.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ABOUT_PKG_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRLINE_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRPORT_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\BANK_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CITY_PKG_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CONTACT_PKG_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\COUNTRY_PKG_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_FACILITY_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FACILITY_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FLIGHT_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\HOME_PAGE_PKG_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\LOGIN_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\PARTENER_PKG_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\RESERVATION_PACKAGE_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\TESTIMONIALS_PKG_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\USER_PKG_2.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DBMS_SQL.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DBMS_OUTPUT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ABOUTUS_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRLINES_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRPORT_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\BANK_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CITY_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CONTACTUS_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\COUNTRY_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_FACILITIES_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FACILITY_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FLIGHT_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\HOME_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\LOGIN_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\PARTNER_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\RESERVATION_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\ROLE_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\TESTIMONIAL_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\USERS_CONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\AIRPORT_REFCONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\CITY_REFCONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\DEGREE_FACILITIES_REFCONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\FLIGHT_REFCONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\LOGIN_REFCONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\PARTNER_REFCONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\RESERVATION_REFCONSTRAINT.sql
@C:\Users\wasse\Desktop\Ta7alf\Flight Database\TESTIMONIAL_REFCONSTRAINT.sql
